#[test_only]
module challenge::arena_tests;

// ========================== DO NOT EDIT THIS FILE ==========================

use challenge::arena::{Self, Arena, ArenaCreated, ArenaCompleted};
use challenge::hero::{Self, Hero, HeroMetadata};
use challenge::marketplace::{Self, ListHero, AdminCap, EInvalidPayment, HeroListed, HeroBought};
use sui::coin;
use sui::sui::SUI;
use sui::test_scenario::{Self as ts, next_tx};
use sui::test_utils::destroy;

// Error codes for assertions
const EHeroNameMismatch: u64 = 1;
const EHeroImageUrlMismatch: u64 = 2;
const EHeroPowerMismatch: u64 = 3;
const EHeroPriceMismatch: u64 = 4;
const EHeroNotCreated: u64 = 5;
const EHeroNotTransferred: u64 = 6;
const EListHeroNotShared: u64 = 7;
const EArenaNotShared: u64 = 8;
const EHeroAmountMismatch: u64 = 9;
const EDidNotEmitEvent: u64 = 10;

const SENDER: address = @0x1;
const RECIPIENT: address = @0x2;
const PRICE: u64 = 1_000_000_000; // 1 SUI in MIST

#[test]
fun test_create_hero() {
    let mut scenario = ts::begin(SENDER);

    // Create a hero
    {
        hero::create_hero(
            b"Ali".to_string(),
            b"https://example.com/ali.png".to_string(),
            9000,
            scenario.ctx(),
        );
    };

    // Move to next transaction to access the created hero
    next_tx(&mut scenario, SENDER);

    // Verify hero was created and test getter functions
    assert!(ts::has_most_recent_for_sender<Hero>(&scenario), EHeroNotCreated);

    // Will revert if taking object which is not shared
    let metadata = scenario.take_immutable<HeroMetadata>();

    {
        let hero = ts::take_from_sender<Hero>(&scenario);
        // Test getter functions
        assert!(hero::hero_name(&hero) == b"Ali".to_string(), EHeroNameMismatch);
        assert!(
            hero::hero_image_url(&hero) == b"https://example.com/ali.png".to_string(),
            EHeroImageUrlMismatch,
        );
        assert!(hero::hero_power(&hero) == 9000, EHeroPowerMismatch);
        ts::return_to_sender(&scenario, hero);
    };

    destroy(metadata);
    ts::end(scenario);
}

#[test]
fun test_transfer_hero() {
    let mut scenario = ts::begin(SENDER);

    // Create a hero first
    {
        hero::create_hero(
            b"Serkan".to_string(),
            b"https://example.com/serkan.png".to_string(),
            8500,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, SENDER);

    // Transfer the hero to recipient
    {
        let hero = ts::take_from_sender<Hero>(&scenario);
        transfer::public_transfer(hero, RECIPIENT)
    };

    // Move to next transaction as recipient
    next_tx(&mut scenario, RECIPIENT);

    // Verify hero is now owned by recipient
    assert!(ts::has_most_recent_for_address<Hero>(RECIPIENT), EHeroNotTransferred);

    ts::end(scenario);
}

#[test]
fun test_list_hero() {
    let mut scenario = ts::begin(SENDER);

    // Create a hero first
    {
        hero::create_hero(
            b"Mantas".to_string(),
            b"https://example.com/mantas.png".to_string(),
            7500,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, SENDER);

    // List the hero for sale
    {
        let hero = ts::take_from_sender<Hero>(&scenario);

        marketplace::list_hero(hero, PRICE, scenario.ctx());
        assert!(sui::event::events_by_type<HeroListed>().length() == 1, EDidNotEmitEvent);
    };

    next_tx(&mut scenario, SENDER);

    // Verify ListHero object was created and shared
    assert!(ts::has_most_recent_shared<ListHero>(), EListHeroNotShared);

    ts::end(scenario);
}

#[test]
fun test_buy_hero() {
    let mut scenario = ts::begin(SENDER);

    // Create and list a hero
    {
        hero::create_hero(
            b"Teo".to_string(),
            b"https://example.com/teo.png".to_string(),
            6000,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, SENDER);

    {
        let hero = ts::take_from_sender<Hero>(&scenario);

        marketplace::list_hero(hero, PRICE, scenario.ctx());
    };

    next_tx(&mut scenario, RECIPIENT);

    // Buy the hero
    {
        let coin = coin::mint_for_testing<SUI>(PRICE, scenario.ctx());
        let list_hero = ts::take_shared<ListHero>(&scenario);

        marketplace::buy_hero(list_hero, coin, scenario.ctx());
        assert!(sui::event::events_by_type<HeroBought>().length() == 1, EDidNotEmitEvent);
    };

    next_tx(&mut scenario, RECIPIENT);

    // Verify buyer received the hero
    assert!(ts::has_most_recent_for_address<Hero>(RECIPIENT), EHeroNotTransferred);

    {
        let hero = ts::take_from_address<Hero>(&scenario, RECIPIENT);
        assert!(hero::hero_name(&hero) == b"Teo".to_string(), EHeroNameMismatch);
        assert!(hero::hero_power(&hero) == 6000, EHeroPowerMismatch);
        ts::return_to_address(RECIPIENT, hero);
    };

    ts::end(scenario);
}

#[test]
#[expected_failure(abort_code = EInvalidPayment)]
fun test_buy_hero_payment_too_low() {
    let mut scenario = ts::begin(SENDER);

    // Create and list a hero
    {
        hero::create_hero(
            b"Teo".to_string(),
            b"https://example.com/teo.png".to_string(),
            6000,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, SENDER);

    {
        let hero = ts::take_from_sender<Hero>(&scenario);

        marketplace::list_hero(hero, PRICE, scenario.ctx());
    };

    next_tx(&mut scenario, RECIPIENT);

    // Buy the hero
    {
        let too_low_payment = coin::mint_for_testing<SUI>(PRICE / 2, scenario.ctx());
        let list_hero = ts::take_shared<ListHero>(&scenario);

        marketplace::buy_hero(list_hero, too_low_payment, scenario.ctx());
    };

    next_tx(&mut scenario, RECIPIENT);

    scenario.end();
}

#[test]
#[expected_failure(abort_code = EInvalidPayment)]
fun test_buy_hero_payment_too_high() {
    let mut scenario = ts::begin(SENDER);

    // Create and list a hero
    {
        hero::create_hero(
            b"Teo".to_string(),
            b"https://example.com/teo.png".to_string(),
            6000,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, SENDER);

    {
        let hero = ts::take_from_sender<Hero>(&scenario);

        marketplace::list_hero(hero, PRICE, scenario.ctx());
    };

    next_tx(&mut scenario, RECIPIENT);

    // Buy the hero
    {
        let too_low_payment = coin::mint_for_testing<SUI>(PRICE * 2, scenario.ctx());
        let list_hero = ts::take_shared<ListHero>(&scenario);

        marketplace::buy_hero(list_hero, too_low_payment, scenario.ctx());
    };

    next_tx(&mut scenario, RECIPIENT);

    scenario.end();
}

#[test]
fun test_create_arena() {
    let mut scenario = ts::begin(SENDER);

    // Create a hero first
    {
        hero::create_hero(
            b"Ercan".to_string(),
            b"https://example.com/ercan.png".to_string(),
            8000,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, SENDER);

    // Create arena with the hero
    {
        let hero = ts::take_from_sender<Hero>(&scenario);
        arena::create_arena(hero, scenario.ctx());
        assert!(sui::event::events_by_type<ArenaCreated>().length() == 1, EDidNotEmitEvent);
    };

    next_tx(&mut scenario, SENDER);

    // Verify Arena object was created and shared
    assert!(ts::has_most_recent_shared<Arena>(), EArenaNotShared);

    ts::end(scenario);
}

#[test]
fun test_delist_hero() {
    let mut scenario = ts::begin(SENDER);

    // Create admin cap first
    {
        marketplace::test_init(scenario.ctx());
    };

    next_tx(&mut scenario, SENDER);

    // Create and list a hero
    {
        hero::create_hero(
            b"Ahmet".to_string(),
            b"https://example.com/ahmet.png".to_string(),
            7200,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, SENDER);

    {
        let hero = ts::take_from_sender<Hero>(&scenario);
        marketplace::list_hero(hero, PRICE, scenario.ctx());
    };

    next_tx(&mut scenario, SENDER);

    // Delist the hero using admin cap
    {
        let admin_cap = ts::take_from_sender<AdminCap>(&scenario);
        let list_hero = ts::take_shared<ListHero>(&scenario);

        marketplace::delist(&admin_cap, list_hero);

        ts::return_to_sender(&scenario, admin_cap);
    };

    next_tx(&mut scenario, SENDER);

    // Verify hero was returned to seller
    assert!(ts::has_most_recent_for_sender<Hero>(&scenario), EHeroNotTransferred);

    {
        let hero = ts::take_from_sender<Hero>(&scenario);
        assert!(hero::hero_name(&hero) == b"Ahmet".to_string(), EHeroNameMismatch);
        ts::return_to_sender(&scenario, hero);
    };

    ts::end(scenario);
}

#[test]
fun test_change_the_price() {
    let mut scenario = ts::begin(SENDER);

    // Create admin cap first
    {
        marketplace::test_init(scenario.ctx());
    };

    next_tx(&mut scenario, SENDER);

    // Create and list a hero
    {
        hero::create_hero(
            b"Serkan".to_string(),
            b"https://example.com/serkan.png".to_string(),
            6800,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, SENDER);

    {
        let hero = ts::take_from_sender<Hero>(&scenario);
        marketplace::list_hero(hero, PRICE, scenario.ctx());
    };

    next_tx(&mut scenario, SENDER);

    // Change the price using admin cap
    let new_price = 2000000000; // 2 SUI
    {
        let admin_cap = ts::take_from_sender<AdminCap>(&scenario);
        let mut list_hero = ts::take_shared<ListHero>(&scenario);

        marketplace::change_the_price(&admin_cap, &mut list_hero, new_price);

        ts::return_shared(list_hero);
        ts::return_to_sender(&scenario, admin_cap);
    };

    next_tx(&mut scenario, SENDER);
    {
        let list_hero = ts::take_shared<ListHero>(&scenario);

        assert!(marketplace::listing_price(&list_hero) == new_price, EHeroPriceMismatch);
        ts::return_shared(list_hero);
    };

    ts::end(scenario);
}

#[test]
fun test_battle_cross_user() {
    let mut scenario = ts::begin(SENDER);

    // SENDER creates a hero and battle place
    {
        hero::create_hero(
            b"Kostas".to_string(),
            b"https://example.com/kostas.png".to_string(),
            7500,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, SENDER);

    {
        let hero = ts::take_from_sender<Hero>(&scenario);
        arena::create_arena(hero, scenario.ctx());
    };

    next_tx(&mut scenario, RECIPIENT);

    {
        hero::create_hero(
            b"Adeniyi".to_string(),
            b"https://example.com/adeniyi.png".to_string(),
            8500,
            scenario.ctx(),
        );
    };

    next_tx(&mut scenario, RECIPIENT);

    {
        let hero = ts::take_from_sender<Hero>(&scenario);
        let arena = ts::take_shared<Arena>(&scenario);

        arena::battle(hero, arena, scenario.ctx());
        assert!(sui::event::events_by_type<ArenaCompleted>().length() == 1, EDidNotEmitEvent);
    };

    next_tx(&mut scenario, RECIPIENT);

    // RECIPIENT should have received both heroes (winner gets all)
    // Kostas (8500) > Adeniyi (7500)
    let hero_ids_recipient = ts::ids_for_sender<Hero>(&scenario);
    assert!(hero_ids_recipient.length() == 2, EHeroAmountMismatch);

    // Verify SENDER has no heroes left
    next_tx(&mut scenario, SENDER);
    let hero_ids_sender = ts::ids_for_sender<Hero>(&scenario);
    assert!(hero_ids_sender.length() == 0, EHeroNotTransferred);

    ts::end(scenario);
}
